### ISSUE TITLE
Add text manipulation tools

### ISSUE THREAD

**Issue by mehaase** [infoslack/awesome-web-hacking#27]
Would you consider adding the following tools that are used for manipulating text, i.e. performing various encodings and transformations? It's useful for websec.

* [Encoding tools](https://encoding.tools) (Disclaimer: I created this one)
* [CyberChef](https://gchq.github.io/CyberChef/)

**Comment by infoslack** [comment]
Of course, it looks interesting.
Are you comfortable in sending a PR?
